### ISSUE TITLE
`computeLocalOneCell` hangs on particular cell

### ISSUE THREAD

**Issue by sbrus89** [menta78/alphaBetaLab#2]
Hi Lorenzo,

Thank you for making this package available! I ran into a issue where the code is hanging (for 14 hours) on a particular cell in my mesh. I believe this is occurring in the `computeLocalOneCell` method of the `abCellsEstimator` class. The cell it hangs on is in the Aleutian Islands:

![Screen Shot 2020-09-19 at 8 28 41 AM](https://user-images.githubusercontent.com/3514023/93669541-2435f680-fa52-11ea-811f-ade6bfb6c93b.png)

Here is a close up:

![Screen Shot 2020-09-19 at 8 27 47 AM](https://user-images.githubusercontent.com/3514023/93669512-049ece00-fa52-11ea-83b5-b06bae923eea.png)

I was wondering if you had any intuition on what might be happening here. I would really appreciate any suggestions you have. Thanks again!

**Comment by sbrus89** [comment]
Of course, I'm happy to provide more information as necessary!

**Comment by menta78** [comment]
Hello, and sorry for my delayed reply, apparently I did not receive a notification for this issue. Would you mind to send me the mesh + the script you are using, so I can test it.

**Comment by menta78** [comment]
BTW, I created now a new release tag with some fixes and tuning for the triangular meshes. Though I'm not sure this will solve your problem.

**Comment by sbrus89** [comment]
@menta78, I apologize for keeping this open for over a year now. I recently went back and re-ran with the latest commit and I no longer experienced this issue. Thanks for your help.

**Comment by menta78** [comment]
Thanks Steven, that's good to know.

Lorenzo


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
